### ISSUE TITLE
YAML loading using deprecated loader

### ISSUE THREAD

**Issue by cooperlees** [ibizaman/godaddyip#4]
Got this warning running godaddyip:
```
/usr/local/venvs/godaddyip/lib/python3.8/site-packages/godaddyip/__main__.py:70: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self._config = yaml.load(config_file.read_text()) or {}
```

I'm happy to do this PR to fix this if you agree.

**Comment by ibizaman** [comment]
I’d love a PR for this but check out my comment here saying I switched development effort to another project https://github.com/ibizaman/godaddyip/issues/5?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDI0MDU3NTEwNTE6MTA0NDk1MA%3D%3D#issuecomment-918899015
