### ISSUE TITLE
Add AAAA Support

### ISSUE THREAD

**Issue by cooperlees** [ibizaman/godaddyip#5]
Would you accept a PR to add AAAA (IPv6) record support?

**Comment by ibizaman** [comment]
I would definitely accept it but FYI I switched development to https://github.com/ibizaman/haskell-godaddy instead. Which support AAAA already.

**Comment by cooperlees** [comment]
I can fix this if it breaks. I’ve never written Haskell.

Should I just fork this project? Or you happy for me to add features I’d like?

**Comment by ibizaman** [comment]
@cooperlees both are good to me :) Feel free to add all features you want
